import { NameSet } from "..";
import icons from "../icons";
import { GiBadGnome, GiBirdClaw, GiBoxTrap, GiCat, GiCloak, GiClover, GiDwarfFace, GiElfEar, GiEvilBat, GiEvilMinion, GiFox, GiFrog, GiGoblinHead, GiHyenaHead, GiLizardTongue, GiMermaid, GiMightyForce, GiMonkey, GiOrcHead, GiRat, GiRockGolem, GiSandSnake, GiSpinningSword } from "react-icons/gi";
import { FaHatWizard, FaLeaf } from "react-icons/fa";
import { PiPlantFill } from "react-icons/pi";

export default [
  {
    category: "Western",
    title: "Hero",
    image: icons.hero,
    icon: <GiSpinningSword size="1.3rem" />,
    instructions: "The name should be someone who sounds heroic.",
    data: [
      "**Thalia** the Thundermaiden",
      "**Aragorn** the Rightful King of Gondor",
      "**Mirabel** Starshield",
      "**Thaedon** Guardian of the Ancients",
      "**Caladan** Lord of the Cosmic Realm",
      "**Kvothe** the Arcane Prodigy",
      "Archangel **Avacyn**",
      "**Valdrim** the Stormbringer",
      "**Elysia** the Valiant",
      "**Vaelin** the Braveheart of the Lost Realm",
      "**Elysar** the Windwalker",
      "**Tiriala** Moonbeam",
      "Admiral **Beckett Brass**",
      "**Alesha** Who Smiles at Death",
      "**Lyria** Silvervoice",
      "**Isolde** the Stormbringer",
      "**Revan** Lord of the Thume",
      "**Torrin** of the Broken Blade",
    ],
  },
  {
    category: "Western",
    title: "Benevolent",
    image: icons.benevolent,
    icon: <FaLeaf size="1.3rem" />,
    instructions: "The name should be something who sounds diabolical.",
    data: [
      "**Ebondeath** Dracolich",
      "**Brisela** Voice of Nightmares",
      "**Ashcoat** of the Shadow Swarm",
      "**Asmodeus** the Archfiend",
      "Demonlord **Belzenlok**",
      "**Erebos** God of the Dead",
      "**Gollum** Obsessed Stalker",
      "**Go-Shintai** of Hidden Cruelty",
      "**Griselbrand** He Who Hungers",
      "**Kaervek** the Spiteful",
      "**Kalitas** Traitor of Ghet",
      "**Korlash** Heir to Blackblade",
      "**K'rrik** Son of Yawgmoth",
      "**Mikaeus** the Unhallowed",
      "**Nefarox** Overlord of Grixis",
      "**Ob Nixilis** the Fallen",
      "**Razaketh** the Foulblooded",
      "**Seizan** Perverter of Truth",
      "**Sheoldred** Whispering One",
      "**Skithiryx** the Blight Dragon",
      "**Yawgmoth** Thran Physician",
    ],
  },
  {
    category: "Western",
    title: "Dark Lord",
    image: icons.darkLord,
    icon: <GiEvilBat size="1.3rem" />,
    instructions: "The name should be something who sounds diabolical.",
    data: [
      "**Ebondeath** Dracolich",
      "**Brisela** Voice of Nightmares",
      "**Ashcoat** of the Shadow Swarm",
      "**Asmodeus** the Archfiend",
      "Demonlord **Belzenlok**",
      "**Erebos** God of the Dead",
      "**Gollum** Obsessed Stalker",
      "**Go-Shintai** of Hidden Cruelty",
      "**Griselbrand** He Who Hungers",
      "**Kaervek** the Spiteful",
      "**Kalitas** Traitor of Ghet",
      "**Korlash** Heir to Blackblade",
      "**K'rrik** Son of Yawgmoth",
      "**Mikaeus** the Unhallowed",
      "**Nefarox** Overlord of Grixis",
      "**Ob Nixilis** the Fallen",
      "**Razaketh** the Foulblooded",
      "**Seizan** Perverter of Truth",
      "**Sheoldred** Whispering One",
      "**Skithiryx** the Blight Dragon",
      "**Yawgmoth** Thran Physician",
    ],
  },
  {
    category: "Western",
    title: "Wizard",
    image: icons.wizard,
    icon: <FaHatWizard size="1.3rem" />,
    instructions:
      "The name should be for a wizard. Wise, ancient, and magical.",
    data: [
      "**Arcanis** the Omnipotent",
      "**Arjun** the Shifting Flame",
      "**Azami** Lady of Scrolls",
      "**Barrin** Tolarian Archmage",
      "**Gadwick** the Wizened",
      "**Gandalf** of the Secret Fire",
      "**Gorion** Wise Mentor",
      "**Jace** Vryn's Prodigy",
      "**Naban** Dean of Iteration",
      "**Naru Meha** Master Wizard",
      "**Niv-Mizzet** the Firemind",
      "**Orion** the Mystic Scholar",
      "**Rayne** Academy Chancellor",
      "**Riku** of Two Reflections",
      "**Saruman** of Many Colors",
      "**Teferi** Mage of Zhalfir",
      "**Albus Dumbledore** Headmaster of Magic",
    ],
  },
  {
    category: "Western",
    title: "Grembo",
    image: icons.grembo,
    icon: <GiEvilMinion size="1.3rem" />,
    instructions:
      "The name should be of a small, dirty, sneaky, goofy creature.",
    data: [
      "**Squidgle** Leaky-Toes",
      "**Fremkin** Eater of the Last Piece of Pie",
      "**Skipit** Fish Oil Salesman",
      "**Dobby** the Free Elf",
      "**Grimble** the Puddle Finder",
      "**Smudge** the Dung Seeker",
      "**Kib** the Stench Breather",
    ],
  },
  {
    category: "Western",
    title: "Construct",
    image: icons.construct,
    icon: <GiRockGolem size="1.3rem" />,
    instructions: "The name should be for an ancient construct.",
    data: [
      "**Nosiron** the Sundering Colossus",
      "**Acronis** the Time-Ward Sentinel",
      "**Bosh** Iron Golem",
      "**Golos** Tireless Pilgrim",
      "**Liberator** Urza's Battlethopter",
      "The **Peregrine Dynamo**",
      "**Karn** Silver Golem",
    ],
  },
  {
    category: "Ancestry",
    title: "Dwarf",
    image: icons.dwarf,
    icon: <GiDwarfFace size="1.3rem" />,
    instructions:
      "These should be dwarf names. Dwarves honor their children with names taken from ancestors or dwarven heroes, and it’s quite rare to invent a new name or to borrow a name from another culture for a child. When introducing themselves, dwarves tend to list their family and clan, plus any number of other familial connections and honorifics. Dwarven names usually contain hard consonants and are rarely more or fewer than two syllables.",
    data: [
      "**Agna** the Forge Mistress",
      "**Bodill** Warden of the Deeps",
      "**Dolgrin** Champion of the Stoneskin Clans",
      "**Edrukk** the Iron fist",
      "**Grunyar** the Stoneheart Herald",
      "**Ingra** the Everflame",
      "**Kazmuk** the Runesmith",
      "**Kotri** the Smoky-Eyed",
      "**Lupp** Bringer of Silences",
      "**Morgrym** Hammer of the Depths",
      "**Rogar** the Alestorm Maker",
      "**Rusilka** Healer of the Iron Vein",
      "**Torra** the Gem Whisperer",
      "**Yangrit** the Ruby-Eyed Shieldbearer",
    ],
  },
  {
    category: "Ancestry",
    title: "Elf",
    image: icons.elf,
    icon: <GiElfEar size="1.3rem" />,
    instructions:
      "These should be elf names. An elf keeps their personal name secret among their family, while giving a nickname when meeting other people. This nickname can change over time, due to events in the elf’s life or even on a whim. A single elf might be known by many names by associates of different ages and regions. Elven names consist of multiple syllables and are meant to flow lyrically—at least in the Elven tongue. They so commonly end in “-el” or “-ara” that other cultures sometimes avoid names ending in these syllables to avoid sounding too elven.",
    data: [
      "**Aerel** the Whispering Wind",
      "**Amrunelara** Princess of Moonlight",
      "**Caladrel** Keeper of the Forest Depths",
      "**Dardlara** the Star Voyager",
      "**Faunra** the Enchantress of Emerald Glades",
      "**Heldalel** the Archer of Ethereal Darkness",
      "**Jathal** the Crimson Blade",
      "**Lanliss** the Silent Shadow",
      "**Oparal** the Guardian of Ancient Lore",
      "**Seldlon** the Flame Warden",
      "**Soumral** the Sage of Sunlit Seas",
      "**Talathel** the Sentinel of Sorrowful Skies",
      "**Tessara** the Dreamweaver",
      "**Variel** the Songbird of Venus Dusk",
      "**Yalandlara** the Maiden of Mystic Meadows",
      "**Zordlon** the Storm Bringer",
    ],
  },
  {
    category: "Ancestry",
    title: "Gnome",
    image: icons.gnome,
    icon: <GiBadGnome size="1.3rem" />,
    instructions:
      "These should be gnome names. Gnome names can get quite complex and polysyllabic. They have little interest in familial names, and most children receive their names purely on a parent’s whim. Gnomes rarely concern themselves with how easy their names are to pronounce, and they often go by shorter nicknames. Some even collect and chronicle these nicknames. Among gnomes, the shorter the name, the more feminine it’s considered to be.",
    data: [
      "**Abroshtor** the Enchanted Tinkerer",
      "**Bastargre** the Stonehearted",
      "**Besh** the Fabled Mechanist",
      "**Fijit** the Dreamweaver",
      "**Halungalom** the Star Navigator",
      "**Krolmnite** the Ore Whisperer",
      "**Neji** the Illusionist Alchemist",
      "**Majet** the Clockwork Genius",
      "**Pai** the Sapphire Artisan",
      "**Poshment** the Spellbound Botanist",
      "**Queck** the Mystic Forger",
      "**Trig** the Tempest Tamer",
      "**Zarzuket** the Rune Guardian",
      "**Zatqualmie** the Silvertongue Enigma",
    ],
  },
  {
    category: "Ancestry",
    title: "Goblin",
    image: icons.goblin,
    icon: <GiGoblinHead size="1.3rem" />,
    instructions:
      "These should be goblin names. Goblins keep their names simple. A good name should be easy to pronounce, short enough to shout without getting winded, and taste good to say. The namer often picks a word that rhymes with something they like so that writing songs is easier. Since there aren’t any real traditions regarding naming in goblin culture, children often name themselves once they’re old enough to do something resembling talking.",
    data: [
      "**Ak** the Sly Trickster",
      "**Bokker** Flame-Keeper of the Depths",
      "**Frum** Ravager Below the Mountains",
      "**Guzmuk** the Shadow Skulker",
      "**Krobby** Guardian of the Jade Crypt",
      "**Loohi** Whisperer in the Caverns",
      "**Mazmord** the Crimson Warrior",
      "**Neeka** the Chieftain's Cunning Daughter",
      "**Omgot** Bane of the Bright Daylight",
      "**Ranzak** the Ruthless Marauder",
      "**Rickle** the Mischievous Gadgeteer",
      "**Tup** the Underbridge Menace",
      "**Wakla** the Crafty Trap Smith",
      "**Yonk** the Fierce-Eyed Warcrier",
      "**Zibini** Sorcerer of the Potion Cauldron",
    ],
  },
  {
    category: "Ancestry",
    title: "Halfling",
    image: icons.halfling,
    icon: <GiClover size="1.3rem" />,
    instructions:
      "These should be halfling or hobbit names. Halfling names are usually two to three syllables, with a gentle sound that avoids hard consonants. Preferring their names to sound humble, halflings see overly long or complex names as a sign of arrogance. This goes only for their own people, however—halflings have names that suit them, and they understand that elves and humans might have longer names to suit their own aesthetics. Humans in particular have a tendency to refer to halflings by nicknames, with “Lucky” being common to the point of absurdity.",
    data: [
      "**Anafa** the Sprightly Wanderer",
      "**Antal** Keeper of Treasures",
      "**Bellis** the Evercheerful",
      "**Boram** the Stout-hearted Brewer",
      "**Etune** Whisperer of the Wind",
      "**Filiu** the Leaf Dancer",
      "**Jamir** Guardian of the Harvest",
      "**Kaleb** the Gentle Storyteller",
      "**Linna** the Night Singer",
      "**Marra** the Hearth Keeper",
      "**Miro** the Pipe-weed Farmer",
      "**Rillka** Warden of the Riverbanks",
      "**Sistra** the Jovial Baker",
      "**Sumak** the Star Reader",
      "**Yamyra** the Berry Gatherer",
    ],
  },
  {
    category: "Ancestry",
    title: "Azarketi",
    image: icons.azarketi,
    icon: <GiMermaid size="1.3rem" />,
    instructions:
      "These should be azarketi names. Azarketis often take the names of nautical, weather, or geographical features important to the azarketi's family. Other azarketi groups will choose human names in order to encourage conformity with surface cultures. Some azarketi names have been passed down through so many generations that they still use ancient Azlanti roots or refer to bodies of water that no longer exist.",
    data: [
      "**Aft** the Undaunted Voyager",
      "**Aliz** Mistress of the Aquatic Realm",
      "**Cascade** the Tidal Sorceress",
      "**Delta** the Stormbringer",
      "**Harbor** Guardian of Safe Shores",
      "**Ilani** the Seaborn Enchantress",
      "**Inkua** the Ebb-Flow Seer",
      "**Jib** the Sagasail",
      "**Lagoon** the Ethereal Mariner",
      "**Lobay** the Kraken Whisperer",
      "**Marine** the Serpentbane",
      "**Tidal** the Wave Warden",
      "**Windward** the Gale Dancer",
      "**Zarket** the Trident King",
    ],
  },
  {
    category: "Ancestry",
    title: "Catfolk",
    image: icons.catfolk,
    icon: <GiCat size="1.3rem" />,
    instructions:
      "These should be catfolk names. Catfolk are given short names in their youth. Adolescent catfolk are free to choose a different name when they first leave home, though some simply keep the name they’ve gotten used to. Catfolk love to add titles and honorifics to their names. Some catfolk use their titles exclusively among non-catfolk, and so become known by epithets like Six Fates, Fiend Killer, or Mistcloak.",
    data: [
      "**Alyara** Dreamweaver",
      "**Crinto** the Claw-sworn",
      "**Drewan** Starwhisker",
      "**Espes** the Whispering Predator",
      "**Ferrus** Thunderpurr",
      "**Gerran** Keeper of the Veiled Secrets",
      "**Halhat** Flamefoot",
      "**Hoya** the Starlit Huntress",
      "**Ruun** the Lightning-eyed Warrior",
      "**Sevastin** the Silent Roar",
      "**Tespa** the Moonshadow Dancer",
      "**Aenaris** Whisperwind",
      "**Yonsol** the Light-footed Wanderer",
      "**Zakkar** the Fireheart Voyager",
      "**Zathra** the Spirit-tailed Mystic",
      "**Baishan** Stormpelt",
    ],
  },
  {
    category: "Ancestry",
    title: "Fetchling",
    image: icons.fetchling,
    icon: <GiCloak size="1.3rem" />,
    instructions:
      "These should be fetchling names. Fetchlings adapted to a new world, and their names do the same. These names commonly include phonetic qualities from multiple languages or are simply local cultural names that fetchling families find compelling. Other dominant naming conventions include flowing sounds, harsh or hissing consonants, and surnames that refer to important relatives or community traits.",
    data: [
      "**Amelisce** the Shadow Weaver",
      "**Ashka** of the Ethereal Voids",
      "**Drosil** the Nightbreath",
      "**Eitsanara** the Twilight Whisperer",
      "**Eomva** the Illusionary Trickster",
      "**Ikyamek** the Stargazer of Shadows",
      "**Inva** the Eclipsed Enigma",
      "**Jegan** the Gloomblade",
      "**Lirtae** the Sable Seer",
      "**Meotrai** the Obsidian Sorcerer",
      "**Sorsul** the Veiled Vagabond",
      "**Zokaratz** the Dusk Dweller",
    ],
  },
  {
    category: "Ancestry",
    title: "Gnoll",
    image: icons.gnoll,
    icon: <GiHyenaHead size="1.3rem" />,
    instructions:
      "These should be gnoll names. Newborn kholo are given a root name, typically that of a bone, plant, or animal (though never Hyena, as this is considered narcissistic and arrogant). As a gnoll reaches certain milestones in life, they add descriptors to their name. Root names are often passed down through families, while descriptors are chosen to fit the gnoll's personality, usually in raucous ceremonies.",
    data: [
      "**Baobab** Rooted in Magic",
      "**Jackal** the Cunning Trickster",
      "**Onyx Elephant** in Shadows",
      "**Red Thorn** Heart of the Crimson Rose",
      "**Unbent Iron Reed** Stand of the Steadfast Soldier",
      "**White Acacia** Blossom in the Moonlight",
      "**Wistful Tooth** Bidden Memories of the Wild",
      "**Woodpecker** Feathered Drumbeat of the Forest",
    ],
  },
  {
    category: "Ancestry",
    title: "Grippli",
    image: icons.grippli,
    icon: <GiFrog size="1.3rem" />,
    instructions:
      "These should be grippli names. Grippli names often include resonant vowels and chirped consonants that remain difficult for non-gripplis to vocalize properly. Gripplis that travel widely often adopt one or more names more easily replicated by their associates.",
    data: [
      "**Aalpo'ol** the Enchanted Seer",
      "**Bogwynne** Mistress of the Silent Swamps",
      "**Ctaprak** Holder of the Moonstone Sceptre",
      "**Eegru** the Mystic Raincaller",
      "**Gpoun** the Watercolor Whisperer",
      "**Gruoksh** the Keeper of Emerald Shadows",
      "**Hrrauti** Dancer in the Twilight Mists",
      "**Iopo** the Dawn's Serenade",
      "**Iykiki** Trill of the Golden Frogs",
      "**Kyrsiik** the Firefly Weaver",
      "**Mhruugu** the Hymn of Midnight Marsh",
      "**Oplugo** the Orchid's Guardian",
      "**Quaasol** the Sunstone's Secret",
      "**Yolkuu** the Jade Circlet's Verity",
      "**Ztaal** the Guardian of the Sapphire Springs",
    ],
  },
  {
    category: "Ancestry",
    title: "Hobgoblin",
    image: icons.hobgoblin,
    icon: <GiMightyForce size="1.3rem" />,
    instructions:
      "These should be hobgoblin names. Like goblins, hobgoblin names tend to be simple, though hobgoblin names usually sound more guttural and forceful. On rare occasions, hobgoblins will alter their names, keeping the core but adding aspects, usually in response to an extreme trauma or a life-altering event. Hobgoblins have no surnames, considering them both pointless and presumptuous; an individual’s merits and demerits are to be earned by their actions, not by an association with a particular lineage.",
    data: [
      "**Aze** the Dreamweaver",
      "**Druknar** Guardian of the Shadow Falls",
      "**Ghargam** Sovereign of Emerald Glen",
      "**Hathkren** the Spiritcaller",
      "**Imakra** the Mystic Flame",
      "**Kralaeng** Wielder of the Thunder Hammer",
      "**Mazkol** the Stone Hearted",
      "**Olzu** Keeper of Whispering Winds",
      "**Rezal** the Frostbound",
      "**Sivkrag** the Breaker of Chains",
      "**Volmak** the Iron Fist",
      "**Zornum** Master of the Midnight Sun",
    ],
  },
  {
    category: "Ancestry",
    title: "Kitsune",
    image: icons.kitsune,
    icon: <GiFox size="1.3rem" />,
    instructions:
      "These should be kitsune names. While kitsune have some traditional names, they're more likely to use names that are unremarkable in their local society, the better to pass unnoticed. Some have different names for each form: a kitsune name for their kitsune form, a regional name for a tailless form, and possibly no name at all for a fox form.",
    data: [
      "**Hamako** the Nine-Tailed Conqueror",
      "**Haohiko** the Flame-touched Whisperer",
      "**Kitsukou** Jewel of the Mystic Flame",
      "**Kon** the Shadow Embraced Enigma",
      "**Kwan-la** the Enchantress of Moonlight",
      "**Talaro** the Sage of the Crimson Forest",
    ],
  },
  {
    category: "Ancestry",
    title: "Leshy",
    image: icons.leshy,
    icon: <PiPlantFill size="1.3rem" />,
    instructions:
      "These should be leshy names. Leshies choose and change their names multiple times throughout their lives. These names often represent a facet of their personalities or values, though another common naming convention is to use descriptions of a natural feature they admire. Some leshies even use a cycle of names that changes to align with natural phenomena, such as names based upon the season or the time of day.",
    data: [
      "**Scarlet in Summer** the Blossoming Harbinger",
      "**Verdant Taleweaver** the Ancient Lorekeeper",
      "**Lurking Hunter** the Vigilant Predator",
      "**Masterful Sun Drinker** the Solar Enchanter",
      "**Noon Sky Evening Song** the Lifegiver",
      "**Snowy Pine Branch** the Kind",
      "**Cascading Rapids** the Torrential Voyager",
    ],
  },
  {
    category: "Ancestry",
    title: "Lizardfolk",
    image: icons.lizardfolk,
    icon: <GiLizardTongue size="1.3rem" />,
    instructions:
      "These should be lizardfolk names. Lizardfolk names come from their ancient language and tend to be traditional. Names are typically chosen by the clan’s astrologer in accordance to omens and which star signs are ascendant when an iruxi egg hatches, though occasionally an iruxi’s parents may name a hatchling for an ancestor or a beloved historical hero.",
    data: [
      "**Arasheg** the Twilight Astrologer",
      "**Barashk** the Jade Sentinel",
      "**Essaru** Sovereign of Emerald Marshes",
      "**Tizkar** the Skull Collector",
      "**Enshuk** Warden of the Winding Rivers",
      "**Gishkim** the Jade Claw Wielder",
      "**Hazi** the Silent Predator",
      "**Inishish** Guardian of Constellations",
      "**Kutak** the Crimson Crested",
      "**Nasha** the Sun-Stalker",
      "**Shulkuru** the Bonekeeper",
      "**Utakish** the Opalescent Oracle",
      "**Zelkekek** the Zephyr of the Ziggurat",
    ],
  },
  {
    category: "Ancestry",
    title: "Nagaji",
    image: icons.nagaji,
    icon: <GiSandSnake size="1.3rem" />,
    instructions:
      "These should be nagaji names. Nagaji names vary depending on what region of the world they occupy, but they tend to possess short vowels when they have any at all. Nagaji usually name themselves or allow groups of siblings to name each other as children, a tradition that often sees nagaji eagerly shedding these names for new ones when they reach adulthood.",
    data: [
      "**Adesha** of the Serpent Altar",
      "**Garija** Whisperer of the Emerald Scales",
      "**Kaya** Warden of the Obsidian Coils",
      "**Kuwana** the Sapphire Shieldbearer",
      "**Onok** Conquistador of the Azure Fang",
      "**Paravata** Champion of the Slithering Shadows",
      "**Sheni** Sentinel of the Opal Oasis",
      "**Takasha** Guardian of the Copper Carapace",
      "**Tasi** Herald of the Pythoonstaff",
      "**Ulu** Perceiver of the Hissing Heavens",
      "**Vaski** Emerald Enchanter",
      "**Yulbin** Bringer of the Whispering Whirlwind",
    ],
  },
  {
    category: "Ancestry",
    title: "Orc",
    image: icons.orc,
    icon: <GiOrcHead size="1.3rem" />,
    instructions:
      "These should be orc names. Orcs have a harsh, guttural language, and their naming conventions are no exception. Many orc names are simply the Orcish word for a particularly desirable trait, such as great strength, height, or ferocity. Orcs commonly use either their hold name or a name referencing a particularly memorable accomplishment as their surname.",
    data: [
      "**Arkus** the Ironbane",
      "**Ausk** the Fierce-Eyed",
      "**Durra** the Mountain's Roar",
      "**Grask** the Bloodied Fury",
      "**Grillgiss** Earthbreaker",
      "**Krugga** the Skullsplitter",
      "**Mahja** Wargrider",
      "**Murdut** the Ember's Rage",
      "**Ollak** the Thunderstrike",
      "**Onyat** Moon's Howler",
      "**Thurk** the Silent Blade",
      "**Uirch** the Demon Slayer",
      "**Unach** of the Black Blade",
    ],
  },
  {
    category: "Ancestry",
    title: "Kobold",
    image: icons.kobold,
    icon: <GiBoxTrap size="1.3rem" />,
    instructions:
      "These should be kobold names. A young kobold's given name is rarely more than a syllable or two. However, as they age, achieve status, and accomplish great deeds, kobolds add more syllables to their names, imitating a common draconic practice. Kobolds rarely have surnames except in an effort to better fit into a community, in which case they typically adopt the surname of an inspiring figure in that group.",
    data: [
      "**Azrnak** the Firebreather",
      "**Draahzin** the Clawed Menace",
      "**Enga** the Shadow Whisperer",
      "**Fazgyn** the Crystal Guardian",
      "**Fazij** the Tome Keeper",
      "**Jekkajak** the Tunnel Brute",
      "**Kib** the Silver Tailed",
      "**Kirrok** the Infernal Scale-bearer",
      "**Mirkol** the Gloom Watcher",
      "**Tarka** the Echo of Abyss",
      "**Urkak** the Cavern Chieftain",
      "**Varshez** the Eye of the Deep",
      "**Vroklan** the Scale-carved Warrior",
      "**Zekstikah** the Ember Seeker",
      "**Zgaz** the Fang of Underworld",
    ],
  },
  {
    category: "Ancestry",
    title: "Ratfolk",
    image: icons.ratfolk,
    icon: <GiRat size="1.3rem" />,
    instructions:
      "These should be ratfolk or ysoki names. Every ysoki family has perhaps two dozen names that have been passed down from generation to generation, sometimes with minor alterations or alternative nicknames. A grandfather might be Grivver, for example, while his daughter goes by Griva and her son is simply Griv. Ratfolk are often assigned nicknames and sobriquets by humanoids they interact with, but most ysoki find these names distasteful and endure them only when outside ysoki communities.",
    data: [
      "**Barnan** the Coinfinder",
      "**Chikis** the Shadowmancer",
      "**Chonan** the Silent Weaver",
      "**Deto** of the Twisted Tunnels",
      "**Jass** the Whispering Voice",
      "**Jix** Scavenger of the Beyond",
      "**Knagi** of the Hidden Laugh",
      "**Kubi** the Soulkeeper",
      "**Lolo** the Gleaming Eye",
      "**Ninnec** the Mysterious Enigma",
      "**Nos** the Long-Tailed Sage",
      "**Rak** the Bane of Rats",
      "**Renzi** the Wanderer of the Warrens",
      "**Skigim** the Dust Dancer",
      "**Tali** the Moon Seer",
      "**Zess** the Truth Sniffer",
    ],
  },
  {
    category: "Ancestry",
    title: "Tengu",
    image: icons.tengu,
    icon: <GiBirdClaw size="1.3rem" />,
    instructions:
      "These should be tengu names. Though roosted tengus tend toward more traditional names with the hard consonants often seen in the Tengu language, migrating tengus’ tendency to readily absorb and repurpose the culture of those around them has led to names that combine elements of whatever languages suited the namer’s fancy.",
    data: [
      "**Arkkak** the Wind Whisperer",
      "**Chuko** Keeper of the Silver Wind",
      "**Dolgra** the Storm Bearer",
      "**Dorodara** the Feathered Blade",
      "**Kakkariel** Shadow of the Mountain Peak",
      "**Kora** the Echo in the Mist",
      "**Marrak** Sentinel of the Silverpine",
      "**Mossarah** the Mystic Quill-Wielder",
      "**Pularrka** the Caw of Midnight",
      "**Rarorel** the Pretender",
      "**Ruk** the Silent Feather",
      "**Tak-Tak** the Ruby-Faced",
      "**Tsukotarra** Shield of the Crescent Moon",
    ],
  },
  {
    category: "Ancestry",
    title: "Vanara",
    image: icons.vanara,
    icon: <GiMonkey size="1.3rem" />,
    instructions:
      "These should be vanara names. Newborn vanaras aren't given names other than descriptors of their infant personalities or habits, like “Grip-Hand” or “Wailer.” When they learn to speak, vanaras are given another name based on important historical or mythological figures, or they're given the name of a specific ancestor they resemble in appearance or attitude (or whom their community hopes they'll grow to resemble). The chosen name usually contains consonants or vowels the young vanara frequently uses, as vanaras don't see a lot of use in giving someone a name they can't easily pronounce.",
    data: [
      "**Ashpaka** the Monkey Prince",
      "**Chichipi** Guardian of Jungle Mysteries",
      "**Haangeno** the Wise Sage",
      "**Hasa** the Laughing Trickster",
      "**Huanu** the Keeper of Ancient Secrets",
      "**Kana** the Silent Shadow",
      "**Nammem** the Vigil",
      "**Roprutu** Bearer of the Unseen Sword",
      "**Thathona** the Sacred Guardian",
      "**Unulu** the Whispering Wind",
      "**Vivatu** of the Ruby Orb",
    ],
  },
] as NameSet[];
